/*
 * Adam Asmaca - Ödev 2416501079
 */
package com.mycompany.odevv;

import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ali Efe
 */
public class Odev_2416501079 extends javax.swing.JFrame {

    // DOSYA YOLLARI (SINIF DEĞİŞKENİ) - Madde 8 ve 9
    private static String txtKlasor = "C:\\P2Oyun\\TXTDosyalar\\";
    private static String resimKlasor = "C:\\P2Oyun\\Resimler\\";
    private static String kelimelerDosya = txtKlasor + "kelimeler.txt";
    private static String oyunlarDosya = txtKlasor + "oyunlar.txt";
    private static String logDosya = txtKlasor + "log.txt";
    private static String sifreDosya = txtKlasor + "sifre.txt";

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Odev_2416501079.class.getName());
    private static final DateTimeFormatter TARIH_FORMAT = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss");

    // OYUN DEĞİŞKENLERİ
    private List<String> kelimeListesi = new ArrayList<>();
    private String seciliKelime = "";
    private char[] acilanHarfler;
    private int yanlisSayisi = 0;
    private int saniye = 0;
    private boolean oyunAktif = false;
    private Timer oyunTimer;
    private final List<JLabel> harfLabelleri = new ArrayList<>();
    private final List<Character> hataliHarfler = new ArrayList<>();
    private final Random rnd = new Random();
    private DefaultTableModel modelOyunlar;
    private DefaultTableModel modelLoglar;

    /**
     * Creates new form Odev_2416501079
     */
    public Odev_2416501079() {
        initComponents();
        formHazirla();
    }

    private void formHazirla() {
        setLocationRelativeTo(null);
        lblSure.setText("Süre: 0 sn");
        lblDurum.setText("Oyuna başlamak için butona veya menüyü kullanın");
        modelOyunlar = (DefaultTableModel) jTableOyunlar.getModel();
        modelLoglar = (DefaultTableModel) jTableLoglar.getModel();
        oyunTimer = new Timer(1000, e -> {
            if (oyunAktif) {
                saniye++;
                lblSure.setText("Süre: " + saniye + " sn");
            }
        });
        klasorleriOlustur();
        kelimeleriOku();
        tablolariYenile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelOyun = new javax.swing.JPanel();
        lblSure = new javax.swing.JLabel();
        lblDurum = new javax.swing.JLabel();
        lblHataliDenemeler = new javax.swing.JLabel();
        btnOyunaBasla = new javax.swing.JButton();
        jScrollPaneKelime = new javax.swing.JScrollPane();
        pnlKelime = new javax.swing.JPanel();
        lblAdamResim = new javax.swing.JLabel();
        lblHarfBaslik = new javax.swing.JLabel();
        txtHarf = new javax.swing.JTextField();
        btnHarfTahmin = new javax.swing.JButton();
        lblKelimeBaslik = new javax.swing.JLabel();
        txtKelime = new javax.swing.JTextField();
        btnKelimeTahmin = new javax.swing.JButton();
        jPanelSkor = new javax.swing.JPanel();
        jScrollPaneOyunlar = new javax.swing.JScrollPane();
        jTableOyunlar = new javax.swing.JTable();
        btnSkorTemizle = new javax.swing.JButton();
        jPanelLog = new javax.swing.JPanel();
        jScrollPaneLoglar = new javax.swing.JScrollPane();
        jTableLoglar = new javax.swing.JTable();
        btnLogTemizle = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOyun = new javax.swing.JMenu();
        mnuOyunaBasla = new javax.swing.JMenuItem();
        mnuYenidenBasla = new javax.swing.JMenuItem();
        mnuCikis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adam Asmaca - 2416501079");

        lblSure.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSure.setText("Sure: 0 sn");

        lblDurum.setText("Oyuna baslamak icin butona veya menuyu kullanin");

        lblHataliDenemeler.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblHataliDenemeler.setText("Hatalı denemeler: -");

        btnOyunaBasla.setText("Oyuna Basla");
        btnOyunaBasla.addActionListener(this::btnOyunaBaslaActionPerformed);

        jScrollPaneKelime.setBorder(javax.swing.BorderFactory.createTitledBorder("Kelime"));
        jScrollPaneKelime.setViewportView(pnlKelime);

        lblAdamResim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdamResim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAdamResim.setMinimumSize(new java.awt.Dimension(250, 250));
        lblAdamResim.setPreferredSize(new java.awt.Dimension(250, 250));

        lblHarfBaslik.setText("Harf Tahmini:");

        txtHarf.setColumns(3);

        btnHarfTahmin.setText("Harf Dene");
        btnHarfTahmin.addActionListener(this::btnHarfTahminActionPerformed);

        lblKelimeBaslik.setText("Kelime Tahmini:");

        txtKelime.setColumns(15);

        btnKelimeTahmin.setText("Kelime Dene");
        btnKelimeTahmin.addActionListener(this::btnKelimeTahminActionPerformed);

        javax.swing.GroupLayout jPanelOyunLayout = new javax.swing.GroupLayout(jPanelOyun);
        jPanelOyun.setLayout(jPanelOyunLayout);
        jPanelOyunLayout.setHorizontalGroup(
            jPanelOyunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOyunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdamResim, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelOyunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOyunLayout.createSequentialGroup()
                        .addComponent(lblSure)
                        .addGap(18, 18, 18)
                        .addComponent(lblDurum)
                        .addGap(18, 18, 18)
                        .addComponent(btnOyunaBasla))
                    .addComponent(jScrollPaneKelime)
                    .addComponent(lblHataliDenemeler)
                    .addGroup(jPanelOyunLayout.createSequentialGroup()
                        .addComponent(lblHarfBaslik)
                        .addGap(18, 18, 18)
                        .addComponent(txtHarf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHarfTahmin)
                        .addGap(18, 18, 18)
                        .addComponent(lblKelimeBaslik)
                        .addGap(18, 18, 18)
                        .addComponent(txtKelime, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKelimeTahmin)))
                .addContainerGap())
        );
        jPanelOyunLayout.setVerticalGroup(
            jPanelOyunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOyunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOyunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdamResim, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelOyunLayout.createSequentialGroup()
                        .addGroup(jPanelOyunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSure)
                            .addComponent(lblDurum)
                            .addComponent(btnOyunaBasla))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneKelime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHataliDenemeler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelOyunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHarfBaslik)
                            .addComponent(txtHarf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHarfTahmin)
                            .addComponent(lblKelimeBaslik)
                            .addComponent(txtKelime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKelimeTahmin))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Oyun Oynama", jPanelOyun);

        jTableOyunlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarih", "Sure (sn)", "Sonuc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneOyunlar.setViewportView(jTableOyunlar);

        btnSkorTemizle.setText("Temizle");
        btnSkorTemizle.addActionListener(this::btnSkorTemizleActionPerformed);

        javax.swing.GroupLayout jPanelSkorLayout = new javax.swing.GroupLayout(jPanelSkor);
        jPanelSkor.setLayout(jPanelSkorLayout);
        jPanelSkorLayout.setHorizontalGroup(
            jPanelSkorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneOyunlar)
            .addComponent(btnSkorTemizle, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelSkorLayout.setVerticalGroup(
            jPanelSkorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneOyunlar)
            .addComponent(btnSkorTemizle)
        );

        jTabbedPane1.addTab("Eski Skorlar", jPanelSkor);

        jTableLoglar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarih", "Aciklama"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneLoglar.setViewportView(jTableLoglar);

        btnLogTemizle.setText("Temizle");
        btnLogTemizle.addActionListener(this::btnLogTemizleActionPerformed);

        javax.swing.GroupLayout jPanelLogLayout = new javax.swing.GroupLayout(jPanelLog);
        jPanelLog.setLayout(jPanelLogLayout);
        jPanelLogLayout.setHorizontalGroup(
            jPanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneLoglar)
            .addComponent(btnLogTemizle, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelLogLayout.setVerticalGroup(
            jPanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneLoglar)
            .addComponent(btnLogTemizle)
        );

        jTabbedPane1.addTab("Loglar", jPanelLog);

        jMenuOyun.setText("Oyun");

        mnuOyunaBasla.setText("Oyuna Basla");
        mnuOyunaBasla.addActionListener(this::mnuOyunaBaslaActionPerformed);
        jMenuOyun.add(mnuOyunaBasla);

        mnuYenidenBasla.setText("Oyunu Yeniden Baslat");
        mnuYenidenBasla.addActionListener(this::mnuYenidenBaslaActionPerformed);
        jMenuOyun.add(mnuYenidenBasla);

        mnuCikis.setText("Cikis");
        mnuCikis.addActionListener(this::mnuCikisActionPerformed);
        jMenuOyun.add(mnuCikis);

        jMenuBar1.add(jMenuOyun);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuOyunaBaslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOyunaBaslaActionPerformed
        oyunaBasla();
    }//GEN-LAST:event_mnuOyunaBaslaActionPerformed

    private void mnuYenidenBaslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuYenidenBaslaActionPerformed
        oyunaBasla();
    }//GEN-LAST:event_mnuYenidenBaslaActionPerformed

    private void mnuCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCikisActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuCikisActionPerformed

    private void btnOyunaBaslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOyunaBaslaActionPerformed
        oyunaBasla();
    }//GEN-LAST:event_btnOyunaBaslaActionPerformed

    private void btnHarfTahminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarfTahminActionPerformed
        harfTahminYap();
    }//GEN-LAST:event_btnHarfTahminActionPerformed

    private void btnKelimeTahminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelimeTahminActionPerformed
        kelimeTahminYap();
    }//GEN-LAST:event_btnKelimeTahminActionPerformed

    private void btnSkorTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkorTemizleActionPerformed
        skorlariTemizle();
    }//GEN-LAST:event_btnSkorTemizleActionPerformed

    private void btnLogTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogTemizleActionPerformed
        loglariTemizle();
    }//GEN-LAST:event_btnLogTemizleActionPerformed

    // ==================== OYUN MANTIĞI ====================

    private void kelimeleriOku() {
        kelimeListesi.clear();
        try {
            File f = new File(kelimelerDosya);
            if (!f.exists()) {
                lblDurum.setText("kelimeler.txt bulunamadı!");
                return;
            }
            List<String> satirlar = Files.readAllLines(f.toPath(), Charset.defaultCharset());
            for (String s : satirlar) {
                String k = s.trim();
                if (k.length() >= 6) {
                    kelimeListesi.add(k.toUpperCase(Locale.forLanguageTag("tr")));
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Kelimeler okunamadı: " + ex.getMessage());
        }
    }

    private void oyunaBasla() {
        if (kelimeListesi.isEmpty()) {
            kelimeleriOku();
        }
        if (kelimeListesi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Oynanacak kelime yok. Dosyayı kontrol edin:\n" + kelimelerDosya);
            return;
        }

        oyunTimer.stop();
        yanlisSayisi = 0;
        hataliHarfler.clear();
        hataliHarfleriGuncelle();
        saniye = 0;
        oyunAktif = true;
        lblSure.setText("Süre: 0 sn");
        lblAdamResim.setIcon(null);
        txtHarf.setText("");
        txtKelime.setText("");

        int index = rnd.nextInt(kelimeListesi.size());
        seciliKelime = kelimeListesi.get(index);
        acilanHarfler = new char[seciliKelime.length()];
        for (int i = 0; i < acilanHarfler.length; i++) {
            acilanHarfler[i] = '*';
        }

        harfPanelleriniOlustur();
        lblDurum.setText("Tahmine başlayın.");
        jTabbedPane1.setSelectedIndex(0);
        oyunTimer.start();
        logYaz("Yeni oyun başlatıldı");
    }

    private void harfPanelleriniOlustur() {
        pnlKelime.removeAll();
        harfLabelleri.clear();
        for (int i = 0; i < seciliKelime.length(); i++) {
            JLabel lbl = new JLabel("*");
            lbl.setFont(new Font("Segoe UI", Font.BOLD, 28));
            harfLabelleri.add(lbl);
            pnlKelime.add(lbl);
        }
        pnlKelime.revalidate();
        pnlKelime.repaint();
    }

    private void harfleriGuncelle() {
        for (int i = 0; i < seciliKelime.length(); i++) {
            char c = acilanHarfler[i];
            harfLabelleri.get(i).setText(c == '*' ? "*" : String.valueOf(c));
        }
    }

    private boolean kelimeTamamMi() {
        for (char c : acilanHarfler) {
            if (c == '*') {
                return false;
            }
        }
        return true;
    }

    private void harfTahminYap() {
        if (!oyunAktif) {
            JOptionPane.showMessageDialog(this, "Önce oyuna başlayın.");
            return;
        }
        String giris = txtHarf.getText().trim().toUpperCase(Locale.forLanguageTag("tr"));
        if (giris.length() != 1) {
            JOptionPane.showMessageDialog(this, "Tek harf girin.");
            return;
        }
        char harf = giris.charAt(0);
        boolean bulundu = false;
        for (int i = 0; i < seciliKelime.length(); i++) {
            if (seciliKelime.charAt(i) == harf) {
                acilanHarfler[i] = harf;
                bulundu = true;
            }
        }
        txtHarf.setText("");
        logYaz("Harf tahmini: " + harf + (bulundu ? " (doğru)" : " (yanlış)"));
        if (bulundu) {
            harfleriGuncelle();
            if (kelimeTamamMi()) {
                oyunBitti(true);
            }
        } else {
            hataliHarfEkle(harf);
            yanlisTahmin();
        }
    }

    private void hataliHarfEkle(char harf) {
        for (char c : hataliHarfler) {
            if (c == harf) {
                return;
            }
        }
        hataliHarfler.add(harf);
        hataliHarfleriGuncelle();
    }

    private void hataliHarfleriGuncelle() {
        if (hataliHarfler.isEmpty()) {
            lblHataliDenemeler.setText("Hatalı denemeler: -");
            return;
        }
        StringBuilder sb = new StringBuilder("Hatalı denemeler: ");
        for (int i = 0; i < hataliHarfler.size(); i++) {
            if (i > 0) {
                sb.append(", ");
            }
            sb.append(hataliHarfler.get(i));
        }
        lblHataliDenemeler.setText(sb.toString());
    }

    private void kelimeTahminYap() {
        if (!oyunAktif) {
            JOptionPane.showMessageDialog(this, "Önce oyuna başlayın.");
            return;
        }
        String giris = txtKelime.getText().trim().toUpperCase(Locale.forLanguageTag("tr"));
        if (giris.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kelime girin.");
            return;
        }
        txtKelime.setText("");
        logYaz("Kelime tahmini: " + giris);
        if (giris.equals(seciliKelime)) {
            for (int i = 0; i < seciliKelime.length(); i++) {
                acilanHarfler[i] = seciliKelime.charAt(i);
            }
            harfleriGuncelle();
            oyunBitti(true);
        } else {
            yanlisTahmin();
        }
    }

    private void yanlisTahmin() {
        yanlisSayisi++;
        resimGoster(yanlisSayisi);
        lblDurum.setText("Yanlış tahmin: " + yanlisSayisi + " / 11");
        if (yanlisSayisi >= 11) {
            JOptionPane.showMessageDialog(this, "11 yanlış tahmin! Kelime: " + seciliKelime);
            oyunBitti(false);
        }
    }

    private void resimGoster(int adim) {
        if (adim < 1 || adim > 11) {
            return;
        }
        String yol = resimDosyaYoluBul(adim);
        if (yol == null) {
            lblDurum.setText("Resim bulunamadı: " + resimKlasor + adim + ".jpg");
            return;
        }
        ImageIcon icon = new ImageIcon(yol);
        Image img = icon.getImage().getScaledInstance(250, 250, Image.SCALE_SMOOTH);
        lblAdamResim.setIcon(new ImageIcon(img));
        lblAdamResim.revalidate();
        lblAdamResim.repaint();
    }

    private String resimDosyaYoluBul(int adim) {
        String[] uzantilar = {".jpg", ".png"};
        for (String uz : uzantilar) {
            File f = new File(resimKlasor + adim + uz);
            if (f.isFile()) {
                return f.getAbsolutePath();
            }
        }
        return null;
    }

    private void oyunBitti(boolean kazandi) {
        oyunAktif = false;
        oyunTimer.stop();
        String sonuc = kazandi ? "Kazandı" : "Kaybetti";
        lblDurum.setText("Oyun bitti: " + sonuc + " | Kelime: " + seciliKelime);
        oyunKaydet(sonuc);
        tablolariYenile();
        JOptionPane.showMessageDialog(this,
                "Oyun Sonucu: " + (kazandi ? "Kazandı" : "Kaybetti")
                + "\nSüre: " + saniye + " sn");
        if (kazandi) {
            lblDurum.setText("Tebrikler!");
        }
    }

    private void oyunKaydet(String sonuc) {
        try {
            String satir = LocalDateTime.now().format(TARIH_FORMAT) + ";" + saniye + ";" + sonuc;
            Path yol = new File(oyunlarDosya).toPath();
            Files.write(yol, (satir + System.lineSeparator()).getBytes(Charset.defaultCharset()),
                    StandardOpenOption.CREATE, StandardOpenOption.APPEND);
            logYaz("Oyun kaydedildi: " + sonuc + " - " + saniye + " sn");
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void tablolariYenile() {
        skorTablosunuDoldur();
        logTablosunuDoldur();
    }

    private void skorTablosunuDoldur() {
        modelOyunlar.setRowCount(0);
        try {
            File f = new File(oyunlarDosya);
            if (!f.exists()) {
                return;
            }
            List<String> satirlar = Files.readAllLines(f.toPath(), Charset.defaultCharset());
            for (String satir : satirlar) {
                String[] parca = satir.split(";");
                if (parca.length >= 3) {
                    modelOyunlar.addRow(new Object[]{parca[0], parca[1], parca[2]});
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void logTablosunuDoldur() {
        modelLoglar.setRowCount(0);
        try {
            File f = new File(logDosya);
            if (!f.exists()) {
                return;
            }
            List<String> satirlar = Files.readAllLines(f.toPath(), Charset.defaultCharset());
            for (String satir : satirlar) {
                int nokta = satir.indexOf(';');
                if (nokta > 0) {
                    modelLoglar.addRow(new Object[]{
                        satir.substring(0, nokta),
                        satir.substring(nokta + 1)
                    });
                } else {
                    modelLoglar.addRow(new Object[]{satir, ""});
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void skorlariTemizle() {
        if (!sifreDogrula("Skorları temizlemek için şifre")) {
            return;
        }
        try {
            File f = new File(oyunlarDosya);
            if (f.exists()) {
                Files.write(f.toPath(), new byte[0]);
            }
            skorTablosunuDoldur();
            JOptionPane.showMessageDialog(this, "Oyun skorları temizlendi.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Temizlenemedi: " + ex.getMessage());
        }
    }

    private void loglariTemizle() {
        if (!sifreDogrula("Logları temizlemek için şifre")) {
            return;
        }
        try {
            File f = new File(logDosya);
            if (f.exists()) {
                Files.write(f.toPath(), new byte[0]);
            }
            logTablosunuDoldur();
            JOptionPane.showMessageDialog(this, "Loglar temizlendi.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Temizlenemedi: " + ex.getMessage());
        }
    }

    // ==================== ŞİFRE VE LOG (AYNI DOSYA) ====================

    private static void klasorleriOlustur() {
        new File(txtKlasor).mkdirs();
        new File(resimKlasor).mkdirs();
    }

    private static void logYaz(String mesaj) {
        try {
            klasorleriOlustur();
            String satir = LocalDateTime.now().format(TARIH_FORMAT) + ";" + mesaj;
            Path yol = new File(logDosya).toPath();
            Files.write(yol, (satir + System.lineSeparator()).getBytes(Charset.defaultCharset()),
                    StandardOpenOption.CREATE, StandardOpenOption.APPEND);
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private static String dosyadanSifreOku() {
        try {
            File f = new File(sifreDosya);
            if (!f.exists()) {
                return null;
            }
            List<String> satirlar = Files.readAllLines(f.toPath(), Charset.defaultCharset());
            if (satirlar.isEmpty()) {
                return null;
            }
            return satirlar.get(0).trim();
        } catch (Exception ex) {
            return null;
        }
    }

    private static void sifreKaydet(String sifre) {
        try {
            klasorleriOlustur();
            Path yol = new File(sifreDosya).toPath();
            Files.write(yol, sifre.getBytes(Charset.defaultCharset()),
                    StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Şifre kaydedilemedi: " + ex.getMessage());
        }
    }

    private static String sifreSor(String baslik) {
        JPasswordField pf = new JPasswordField();
        int sonuc = JOptionPane.showConfirmDialog(null, pf, baslik, JOptionPane.OK_CANCEL_OPTION);
        if (sonuc == JOptionPane.OK_OPTION) {
            return new String(pf.getPassword());
        }
        return null;
    }

    private static boolean ilkSifreBelirle() {
        String sifre1 = sifreSor("İlk kez giriş - Yeni şifre belirleyin");
        if (sifre1 == null || sifre1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Şifre boş olamaz. Program kapanıyor.");
            return false;
        }
        String sifre2 = sifreSor("Şifreyi tekrar girin");
        if (sifre2 == null || !sifre1.equals(sifre2)) {
            JOptionPane.showMessageDialog(null, "Şifreler uyuşmadı. Program kapanıyor.");
            return false;
        }
        sifreKaydet(sifre1);
        logYaz("İlk şifre belirlendi");
        JOptionPane.showMessageDialog(null, "Şifreniz kaydedildi.");
        return true;
    }

    private static boolean sifreKontrolEt() {
        String kayitli = dosyadanSifreOku();
        if (kayitli == null || kayitli.isEmpty()) {
            return ilkSifreBelirle();
        }
        int deneme = 0;
        while (deneme < 3) {
            String girilen = sifreSor("Şifre girin (Kalan hak: " + (3 - deneme) + ")");
            if (girilen == null) {
                logYaz("Şifre girişi iptal edildi");
                return false;
            }
            if (girilen.equals(kayitli)) {
                logYaz("Giriş - şifre doğru");
                return true;
            }
            deneme++;
            logYaz("Hatalı şifre denemesi (" + deneme + "/3)");
            JOptionPane.showMessageDialog(null, "Hatalı şifre! Kalan: " + (3 - deneme));
        }
        JOptionPane.showMessageDialog(null, "3 kez hatalı giriş. Program kapanıyor.");
        logYaz("3 hatalı şifre - program sonlandı");
        return false;
    }

    private boolean sifreDogrula(String mesaj) {
        String kayitli = dosyadanSifreOku();
        if (kayitli == null) {
            return false;
        }
        String girilen = sifreSor(mesaj);
        if (girilen != null && girilen.equals(kayitli)) {
            logYaz("Şifre doğrulandı: " + mesaj);
            return true;
        }
        logYaz("Şifre doğrulanamadı: " + mesaj);
        JOptionPane.showMessageDialog(this, "Şifre hatalı!");
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
            }

            klasorleriOlustur();
            logYaz("Program başlatıldı");

            if (!sifreKontrolEt()) {
                System.exit(0);
                return;
            }

            Odev_2416501079 form = new Odev_2416501079();
            form.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHarfTahmin;
    private javax.swing.JButton btnKelimeTahmin;
    private javax.swing.JButton btnLogTemizle;
    private javax.swing.JButton btnOyunaBasla;
    private javax.swing.JButton btnSkorTemizle;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuOyun;
    private javax.swing.JPanel jPanelLog;
    private javax.swing.JPanel jPanelOyun;
    private javax.swing.JPanel jPanelSkor;
    private javax.swing.JScrollPane jScrollPaneKelime;
    private javax.swing.JScrollPane jScrollPaneLoglar;
    private javax.swing.JScrollPane jScrollPaneOyunlar;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableLoglar;
    private javax.swing.JTable jTableOyunlar;
    private javax.swing.JLabel lblAdamResim;
    private javax.swing.JLabel lblDurum;
    private javax.swing.JLabel lblHataliDenemeler;
    private javax.swing.JLabel lblHarfBaslik;
    private javax.swing.JLabel lblKelimeBaslik;
    private javax.swing.JLabel lblSure;
    private javax.swing.JMenuItem mnuCikis;
    private javax.swing.JMenuItem mnuOyunaBasla;
    private javax.swing.JMenuItem mnuYenidenBasla;
    private javax.swing.JPanel pnlKelime;
    private javax.swing.JTextField txtHarf;
    private javax.swing.JTextField txtKelime;
    // End of variables declaration//GEN-END:variables
}
